version: "3"
services:
  mariadb:
    image: kalicki2k/alpine-mariadb:10.1
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3306:3306
  owncloud:
    depends_on:
      - mariadb
    image: kalicki2k/alpine-owncloud:10.0.6
    restart: always
    environment:
      - APACHE_RUN_USER=owncloud
      - APACHE_RUN_USER_ID=1000
      - APACHE_RUN_GROUP=owncloud
      - APACHE_RUN_GROUP_ID=1000
    ports:
      - 8080:80
    volumes:
      - .:/var/www/localhost